# Generated by Django 5.1.2 on 2024-10-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Position', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Age', models.CharField(max_length=100)),
            ],
        ),
    ]
