# Generated by Django 5.1.2 on 2024-11-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('MobileNo', models.CharField(max_length=100)),
                ('Course', models.CharField(max_length=100)),
                ('College', models.CharField(max_length=100)),
            ],
        ),
    ]
